config/routes.rb
Rails.application.routes.draw do
  resources :work_types
  resources :work_groups
  resources :works
  resources :users
  resources :user_roles
  resources :user_accesses
  resources :time_lines
  resources :task_types
  resources :task_statuses
  resources :tasks
  resources :stages
  resources :roles
  resources :portfolios
  resources :level_of_efforts
  resources :edit_histories
  resources :environments
  resources :completed_verifications
  resources :companies
  resources :home
  
  get 'portfolios/index' #=> 'greeter#hello'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #get "portfolios/list"
 root 'home#index'


end

app/models/company.rb
class Company < ApplicationRecord
end

app/models/edit_history.rb
class EditHistory < ApplicationRecord
end

app/models/environment.rb
class Environment < ApplicationRecord
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/stage.rb
class Stage < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
end

app/models/task_status.rb
class TaskStatus < ApplicationRecord
end

app/models/task_type.rb
class TaskType < ApplicationRecord
end

app/models/testsql.rb
require 'tiny_tds'    
    print 'test'       
    client = TinyTds::Client.new username: 'RailsUser', password: 'sliaR23#',  
    host: 'amywork/sqlexpress', port: 1433,  
    database: 'ProMaSy', azure:false
    results = client.execute("Select * From Company")
    results.each do |row|  
    puts row  
    end  

app/models/time_line.rb
class TimeLine < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/models/user_access.rb
class UserAccess < ApplicationRecord
end

app/models/user_role.rb
class UserRole < ApplicationRecord
end

app/models/work.rb
class Work < ApplicationRecord
end

app/models/work_group.rb
class WorkGroup < ApplicationRecord
end

app/models/work_type.rb
class WorkType < ApplicationRecord
end

app/controllers/task_types_controller.rb
class TaskTypesController < ApplicationController
  before_action :set_task_type, only: [:show, :edit, :update, :destroy]

  # GET /task_types
  # GET /task_types.json
  def index
    @task_types = TaskType.all
  end

  # GET /task_types/1
  # GET /task_types/1.json
  def show
  end

  # GET /task_types/new
  def new
    @task_type = TaskType.new
  end

  # GET /task_types/1/edit
  def edit
  end

  # POST /task_types
  # POST /task_types.json
  def create
    @task_type = TaskType.new(task_type_params)

    respond_to do |format|
      if @task_type.save
        format.html { redirect_to @task_type, notice: 'Task type was successfully created.' }
        format.json { render :show, status: :created, location: @task_type }
      else
        format.html { render :new }
        format.json { render json: @task_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /task_types/1
  # PATCH/PUT /task_types/1.json
  def update
    respond_to do |format|
      if @task_type.update(task_type_params)
        format.html { redirect_to @task_type, notice: 'Task type was successfully updated.' }
        format.json { render :show, status: :ok, location: @task_type }
      else
        format.html { render :edit }
        format.json { render json: @task_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /task_types/1
  # DELETE /task_types/1.json
  def destroy
    @task_type.destroy
    respond_to do |format|
      format.html { redirect_to task_types_url, notice: 'Task type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task_type
      @task_type = TaskType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_type_params
      params.require(:task_type).permit(:task_type, :is_active, :portfolio_id, :edit_label)
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/task_types_helper.rb
module TaskTypesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/task_types/_form.html.erb
<%= form_with(model: task_type, local: true) do |form| %>
  <% if task_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task_type.errors.count, "error") %> prohibited this task_type from being saved:</h2>

      <ul>
      <% task_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :task_type %>
    <%= form.text_field :task_type, id: :task_type_task_type %>
  </div>

  <div class="field">
    <%= form.label :is_active %>
    <%= form.check_box :is_active, id: :task_type_is_active %>
  </div>

  <div class="field">
    <%= form.label :portfolio_id %>
    <%= form.number_field :portfolio_id, id: :task_type_portfolio_id %>
  </div>

  <div class="field">
    <%= form.label :edit_label %>
    <%= form.text_field :edit_label, id: :task_type_edit_label %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/task_types/edit.html.erb
<h1>Editing Task Type</h1>

<%= render 'form', task_type: @task_type %>

<%= link_to 'Show', @task_type %> |
<%= link_to 'Back', task_types_path %>

app/views/task_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Task Types</h1>

<table>
  <thead>
    <tr>
      <th>Task Type</th>
      <th>Active</th>
      <th>Portfolio</th>
      <th>Edit Label</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @task_types.each do |task_type| %>
      <tr>
        <td><%= task_type.task_type %></td>
        <td><%= task_type.is_active %></td>
        <td><%= task_type.portfolio_id %></td>
        <td><%= task_type.edit_label %></td>
        <td><%= link_to 'Show', task_type %></td>
        <td><%= link_to 'Edit', edit_task_type_path(task_type) %></td>
        <td><%= link_to 'Destroy', task_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task Type', new_task_type_path %>

app/views/task_types/new.html.erb
<h1>New Task Type</h1>

<%= render 'form', task_type: @task_type %>

<%= link_to 'Back', task_types_path %>

app/views/task_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Task Type:</strong>
  <%= @task_type.task_type %>
</p>

<p>
  <strong>Active:</strong>
  <%= @task_type.is_active %>
</p>

<p>
  <strong>Portfolio:</strong>
  <%= @task_type.portfolio_id %>
</p>

<p>
  <strong>Edit Label:</strong>
  <%= @task_type.edit_label %>
</p>

<%= link_to 'Edit', edit_task_type_path(@task_type) %> |
<%= link_to 'Back', task_types_path %>