config/routes.rb
Rails.application.routes.draw do
  resources :work_types
  resources :work_groups
  resources :works
  resources :users
  resources :user_roles
  resources :user_accesses
  resources :time_lines
  resources :task_types
  resources :task_statuses
  resources :tasks
  resources :stages
  resources :roles
  resources :portfolios
  resources :level_of_efforts
  resources :edit_histories
  resources :environments
  resources :completed_verifications
  resources :companies
  resources :home
  
  get 'portfolios/index' #=> 'greeter#hello'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #get "portfolios/list"
 root 'home#index'


end

app/models/company.rb
class Company < ApplicationRecord
end

app/models/edit_history.rb
class EditHistory < ApplicationRecord
end

app/models/environment.rb
class Environment < ApplicationRecord
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/stage.rb
class Stage < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
end

app/models/task_status.rb
class TaskStatus < ApplicationRecord
end

app/models/task_type.rb
class TaskType < ApplicationRecord
end

app/models/testsql.rb
require 'tiny_tds'    
    print 'test'       
    client = TinyTds::Client.new username: 'RailsUser', password: 'sliaR23#',  
    host: 'amywork/sqlexpress', port: 1433,  
    database: 'ProMaSy', azure:false
    results = client.execute("Select * From Company")
    results.each do |row|  
    puts row  
    end  

app/models/time_line.rb
class TimeLine < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/models/user_access.rb
class UserAccess < ApplicationRecord
end

app/models/user_role.rb
class UserRole < ApplicationRecord
end

app/models/work.rb
class Work < ApplicationRecord
end

app/models/work_group.rb
class WorkGroup < ApplicationRecord
end

app/models/work_type.rb
class WorkType < ApplicationRecord
end

app/controllers/work_groups_controller.rb
class WorkGroupsController < ApplicationController
  before_action :set_work_group, only: [:show, :edit, :update, :destroy]

  # GET /work_groups
  # GET /work_groups.json
  def index
    @work_groups = WorkGroup.all
  end

  # GET /work_groups/1
  # GET /work_groups/1.json
  def show
  end

  # GET /work_groups/new
  def new
    @work_group = WorkGroup.new
  end

  # GET /work_groups/1/edit
  def edit
  end

  # POST /work_groups
  # POST /work_groups.json
  def create
    @work_group = WorkGroup.new(work_group_params)

    respond_to do |format|
      if @work_group.save
        format.html { redirect_to @work_group, notice: 'Work group was successfully created.' }
        format.json { render :show, status: :created, location: @work_group }
      else
        format.html { render :new }
        format.json { render json: @work_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /work_groups/1
  # PATCH/PUT /work_groups/1.json
  def update
    respond_to do |format|
      if @work_group.update(work_group_params)
        format.html { redirect_to @work_group, notice: 'Work group was successfully updated.' }
        format.json { render :show, status: :ok, location: @work_group }
      else
        format.html { render :edit }
        format.json { render json: @work_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /work_groups/1
  # DELETE /work_groups/1.json
  def destroy
    @work_group.destroy
    respond_to do |format|
      format.html { redirect_to work_groups_url, notice: 'Work group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work_group
      @work_group = WorkGroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def work_group_params
      params.require(:work_group).permit(:work_type_id, :stage_id, :task_type_id, :role_id, :environment_id, :portfolio_id, :work_group_order)
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/work_groups_helper.rb
module WorkGroupsHelper
end

app/views/work_groups/_form.html.erb
<%= form_with(model: work_group, local: true) do |form| %>
  <% if work_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(work_group.errors.count, "error") %> prohibited this work_group from being saved:</h2>

      <ul>
      <% work_group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :work_type_id %>
    <%= form.number_field :work_type_id, id: :work_group_work_type_id %>
  </div>

  <div class="field">
    <%= form.label :stage_id %>
    <%= form.number_field :stage_id, id: :work_group_stage_id %>
  </div>

  <div class="field">
    <%= form.label :task_type_id %>
    <%= form.number_field :task_type_id, id: :work_group_task_type_id %>
  </div>

  <div class="field">
    <%= form.label :role_id %>
    <%= form.number_field :role_id, id: :work_group_role_id %>
  </div>

  <div class="field">
    <%= form.label :environment_id %>
    <%= form.number_field :environment_id, id: :work_group_environment_id %>
  </div>

  <div class="field">
    <%= form.label :portfolio_id %>
    <%= form.number_field :portfolio_id, id: :work_group_portfolio_id %>
  </div>

  <div class="field">
    <%= form.label :work_group_order %>
    <%= form.number_field :work_group_order, id: :work_group_work_group_order %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/work_groups/edit.html.erb
<h1>Editing Work Group</h1>

<%= render 'form', work_group: @work_group %>

<%= link_to 'Show', @work_group %> |
<%= link_to 'Back', work_groups_path %>

app/views/work_groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Work Groups</h1>

<table>
  <thead>
    <tr>
      <th>Work Type</th>
      <th>Stage</th>
      <th>Task Type</th>
      <th>Role</th>
      <th>Environment</th>
      <th>Portfolio</th>
      <th>Work Group Order</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @work_groups.each do |work_group| %>
      <tr>
        <td><%= work_group.work_type_id %></td>
        <td><%= work_group.stage_id %></td>
        <td><%= work_group.task_type_id %></td>
        <td><%= work_group.role_id %></td>
        <td><%= work_group.environment_id %></td>
        <td><%= work_group.portfolio_id %></td>
        <td><%= work_group.work_group_order %></td>
        <td><%= link_to 'Show', work_group %></td>
        <td><%= link_to 'Edit', edit_work_group_path(work_group) %></td>
        <td><%= link_to 'Destroy', work_group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Work Group', new_work_group_path %>

app/views/work_groups/new.html.erb
<h1>New Work Group</h1>

<%= render 'form', work_group: @work_group %>

<%= link_to 'Back', work_groups_path %>

app/views/work_groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Work Type:</strong>
  <%= @work_group.work_type_id %>
</p>

<p>
  <strong>Stage:</strong>
  <%= @work_group.stage_id %>
</p>

<p>
  <strong>Task Type:</strong>
  <%= @work_group.task_type_id %>
</p>

<p>
  <strong>Role:</strong>
  <%= @work_group.role_id %>
</p>

<p>
  <strong>Environment:</strong>
  <%= @work_group.environment_id %>
</p>

<p>
  <strong>Portfolio:</strong>
  <%= @work_group.portfolio_id %>
</p>

<p>
  <strong>Work Group Order:</strong>
  <%= @work_group.work_group_order %>
</p>

<%= link_to 'Edit', edit_work_group_path(@work_group) %> |
<%= link_to 'Back', work_groups_path %>