config/routes.rb
Rails.application.routes.draw do
  resources :work_types
  resources :work_groups
  resources :works
  resources :users
  resources :user_roles
  resources :user_accesses
  resources :time_lines
  resources :task_types
  resources :task_statuses
  resources :tasks
  resources :stages
  resources :roles
  resources :portfolios
  resources :level_of_efforts
  resources :edit_histories
  resources :environments
  resources :completed_verifications
  resources :companies
  resources :home
  
  get 'portfolios/index' #=> 'greeter#hello'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #get "portfolios/list"
 root 'home#index'


end

app/models/company.rb
class Company < ApplicationRecord
end

app/models/edit_history.rb
class EditHistory < ApplicationRecord
end

app/models/environment.rb
class Environment < ApplicationRecord
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/stage.rb
class Stage < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
end

app/models/task_status.rb
class TaskStatus < ApplicationRecord
end

app/models/task_type.rb
class TaskType < ApplicationRecord
end

app/models/testsql.rb
require 'tiny_tds'    
    print 'test'       
    client = TinyTds::Client.new username: 'RailsUser', password: 'sliaR23#',  
    host: 'amywork/sqlexpress', port: 1433,  
    database: 'ProMaSy', azure:false
    results = client.execute("Select * From Company")
    results.each do |row|  
    puts row  
    end  

app/models/time_line.rb
class TimeLine < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/models/user_access.rb
class UserAccess < ApplicationRecord
end

app/models/user_role.rb
class UserRole < ApplicationRecord
end

app/models/work.rb
class Work < ApplicationRecord
end

app/models/work_group.rb
class WorkGroup < ApplicationRecord
end

app/models/work_type.rb
class WorkType < ApplicationRecord
end

app/controllers/stages_controller.rb
class StagesController < ApplicationController
  before_action :set_stage, only: [:show, :edit, :update, :destroy]

  # GET /stages
  # GET /stages.json
  def index
    @stages = Stage.all
  end

  # GET /stages/1
  # GET /stages/1.json
  def show
  end

  # GET /stages/new
  def new
    @stage = Stage.new
  end

  # GET /stages/1/edit
  def edit
  end

  # POST /stages
  # POST /stages.json
  def create
    @stage = Stage.new(stage_params)

    respond_to do |format|
      if @stage.save
        format.html { redirect_to @stage, notice: 'Stage was successfully created.' }
        format.json { render :show, status: :created, location: @stage }
      else
        format.html { render :new }
        format.json { render json: @stage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stages/1
  # PATCH/PUT /stages/1.json
  def update
    respond_to do |format|
      if @stage.update(stage_params)
        format.html { redirect_to @stage, notice: 'Stage was successfully updated.' }
        format.json { render :show, status: :ok, location: @stage }
      else
        format.html { render :edit }
        format.json { render json: @stage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stages/1
  # DELETE /stages/1.json
  def destroy
    @stage.destroy
    respond_to do |format|
      format.html { redirect_to stages_url, notice: 'Stage was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stage
      @stage = Stage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stage_params
      params.require(:stage).permit(:stage_name, :is_active, :stage_order, :portfolio_id, :edit_label)
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/stages_helper.rb
module StagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/stages/_form.html.erb
<%= form_with(model: stage, local: true) do |form| %>
  <% if stage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stage.errors.count, "error") %> prohibited this stage from being saved:</h2>

      <ul>
      <% stage.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :stage_name %>
    <%= form.text_field :stage_name, id: :stage_stage_name %>
  </div>

  <div class="field">
    <%= form.label :is_active %>
    <%= form.check_box :is_active, id: :stage_is_active %>
  </div>

  <div class="field">
    <%= form.label :stage_order %>
    <%= form.text_field :stage_order, id: :stage_stage_order %>
  </div>

  <div class="field">
    <%= form.label :portfolio_id %>
    <%= form.number_field :portfolio_id, id: :stage_portfolio_id %>
  </div>

  <div class="field">
    <%= form.label :edit_label %>
    <%= form.text_field :edit_label, id: :stage_edit_label %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stages/edit.html.erb
<h1>Editing Stage</h1>

<%= render 'form', stage: @stage %>

<%= link_to 'Show', @stage %> |
<%= link_to 'Back', stages_path %>

app/views/stages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stages</h1>

<table>
  <thead>
    <tr>
      <th>Stage</th>
      <th>Active</th>
      <th>Order</th>
      <th>Portfolio</th>
      <th>Label</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stages.each do |stage| %>
      <tr>
        <td><%= stage.stage_name %></td>
        <td><%= stage.is_active %></td>
        <td><%= stage.stage_order %></td>
        <td><%= stage.portfolio_id %></td>
        <td><%= stage.edit_label %></td>
        <td><%= link_to 'Show', stage %></td>
        <td><%= link_to 'Edit', edit_stage_path(stage) %></td>
        <td><%= link_to 'Destroy', stage, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stage', new_stage_path %>

app/views/stages/new.html.erb
<h1>New Stage</h1>

<%= render 'form', stage: @stage %>

<%= link_to 'Back', stages_path %>

app/views/stages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Stage:</strong>
  <%= @stage.stage_name %>
</p>

<p>
  <strong>Active:</strong>
  <%= @stage.is_active %>
</p>

<p>
  <strong>Order:</strong>
  <%= @stage.stage_order %>
</p>

<p>
  <strong>Portfolio:</strong>
  <%= @stage.portfolio_id %>
</p>

<p>
  <strong>Edit Label:</strong>
  <%= @stage.edit_label %>
</p>

<%= link_to 'Edit', edit_stage_path(@stage) %> |
<%= link_to 'Back', stages_path %>